export const skills = [
  {
    title: 'Color Grading',
    tool: 'DaVinci Resolve',
    icon: '🎨',
    description: 'Master-level color grading — creating mood, atmosphere and visual consistency. From log footage to cinematic LUTs.',
    why: 'Transforms raw footage into a visual signature — the final layer of storytelling.',
  },
  {
    title: 'Video Editing',
    tool: 'Premiere Pro',
    icon: '✂️',
    description: 'Narrative-driven editing that shapes raw footage into compelling stories. Pacing, rhythm, and emotion — all precisely crafted.',
    why: 'Editing is where a film truly comes alive — structure, flow and emotional impact.',
  },
  {
    title: 'Camera Operation & Lens Selection',
    tool: 'Sony / RED / BMPCC',
    icon: '🎥',
    description: 'Deep mastery of cinema cameras and optics — choosing the right lens for mood, depth, and story.',
    why: 'Demonstrates mastery of equipment and ability to choose the right lens for mood/story.',
  },
  {
    title: 'Shot Composition & Framing',
    tool: 'Visual Storytelling',
    icon: '🖼️',
    description: 'Rule of thirds, leading lines, depth layers — a visual vocabulary that commands drama and emotion.',
    why: 'Shows your visual storytelling vocabulary and eye for drama.',
  },
  {
    title: 'Lighting Techniques',
    tool: 'Studio & Natural Light',
    icon: '💡',
    description: 'Sculpting scenes with light — hard, soft, Rembrandt, split, practical. Understanding light is understanding cinema.',
    why: 'Critical for capturing visual style and mood — essential cinematography skill.',
  },
  {
    title: 'Drone Photography & Aerial',
    tool: 'DJI Inspire / Mavic',
    icon: '🚁',
    description: 'Licensed drone pilot delivering breathtaking aerial perspectives — reveal shots, tracking, and orbital moves.',
    why: 'Adds production value and cinematic scale that ground cameras simply cannot achieve.',
  },
  {
    title: 'Sound Design Basics',
    tool: 'Adobe Audition / Resolve',
    icon: '🎧',
    description: 'Ambient sound, foley sync, music selection, and audio mixing — because great film is 50% sound.',
    why: 'Sound design emotionally anchors visuals and builds immersive film worlds.',
  },
  {
    title: 'Motion Graphics',
    tool: 'After Effects',
    icon: '✨',
    description: 'Kinetic typography, lower thirds, transitions, and VFX that add polish to every production.',
    why: 'Elevates production quality and brand identity through purposeful motion design.',
  },
]

export const experiences = [
  {
    company: 'WTL (World Through Lens)',
    role: 'Senior Video Editor & Drone Pilot',
    duration: '2019 — Present',
    years: '5 Years',
    description:
      'Led cinematic productions end-to-end — from pre-production planning to final color grade. Spearheaded aerial cinematography division, managing a fleet of professional drones. Mentored junior videographers and delivered 200+ projects across weddings, commercials, documentaries, and brand films.',
    highlights: [
      'Directed and edited 200+ premium video productions',
      'Built and led the aerial cinematography division',
      'Color graded feature-length documentaries in DaVinci Resolve',
      'Managed full production pipeline from shoot to delivery',
      'Mentored a team of 5 junior videographers and editors',
    ],
    logo: '🎬',
  },
]

export const navLinks = [
  { label: 'Home',         href: '#home' },
  { label: 'About',        href: '#about' },
  { label: 'Skills',       href: '#skills' },
  { label: 'Works',        href: '#works' },
  { label: 'Experience',   href: '#experience' },
  { label: 'Testimonials', href: '#testimonials' },
  { label: 'Contact',      href: '#contact' },
]

export const fallbackWorks = [
  {
    _id: '1',
    title: 'Cinematic Reel',
    description: 'A breathtaking cinematic reel — stunning visuals, color graded in DaVinci Resolve.',
    videoUrl: 'https://www.youtube.com/embed/z_EU0Psi358',
    thumbnail: 'https://img.youtube.com/vi/z_EU0Psi358/maxresdefault.jpg',
    category: 'Cinematography',
    tags: ['Cinematic', 'Color Grade'],
    featured: true,
  },
  {
    _id: '2',
    title: 'Aerial Drone Showreel',
    description: 'Stunning aerial footage captured with professional DJI — sweeping landscapes and urban reveals.',
    videoUrl: 'https://www.youtube.com/embed/2OpwNs0ODzk',
    thumbnail: 'https://img.youtube.com/vi/2OpwNs0ODzk/maxresdefault.jpg',
    category: 'Drone',
    tags: ['Aerial', 'Drone', '4K'],
    featured: true,
  },
  {
    _id: '3',
    title: 'Commercial Brand Film',
    description: 'High-end commercial production — product close-ups, lifestyle footage, and cinematic storytelling.',
    videoUrl: 'https://www.youtube.com/embed/PEh16Bjx0Ts',
    thumbnail: 'https://img.youtube.com/vi/PEh16Bjx0Ts/maxresdefault.jpg',
    category: 'Commercial',
    tags: ['Brand', 'Commercial'],
    featured: true,
  },
  {
    _id: '4',
    title: 'Short Film',
    description: 'Short drama shot on cinema camera, graded in DaVinci Resolve with a signature cinematic look.',
    videoUrl: 'https://www.youtube.com/embed/sjmPxG2WU-M',
    thumbnail: 'https://img.youtube.com/vi/sjmPxG2WU-M/maxresdefault.jpg',
    category: 'Short Film',
    tags: ['Short Film', 'Drama'],
    featured: false,
  },
  {
    _id: '5',
    title: 'Content Creator Reel',
    description: 'Dynamic content creation reel — fast cuts, engaging visuals crafted for social media platforms.',
    videoUrl: 'https://www.youtube.com/embed/6f9ajuYjQLg',
    thumbnail: 'https://img.youtube.com/vi/6f9ajuYjQLg/maxresdefault.jpg',
    category: 'Content Creator',
    tags: ['Content', 'Social Media', 'Reels'],
    featured: false,
  },
  {
    _id: '6',
    title: 'Wedding Cinematic Film',
    description: 'Emotional wedding film — every tender moment captured with cinematic flair and drone aerials.',
    videoUrl: 'https://www.youtube.com/embed/31pwJIsuMxc',
    thumbnail: 'https://img.youtube.com/vi/31pwJIsuMxc/maxresdefault.jpg',
    category: 'Editing',
    tags: ['Wedding', 'Emotional'],
    featured: false,
  },
]

export const fallbackTestimonials = [
  {
    _id: '1',
    name: 'Rahul Verma',
    role: 'Director',
    company: 'Cinecraft Studios',
    message: "Shriram's eye for composition is extraordinary. He captured our short film with a visual poetry I've rarely seen. His DaVinci grading transformed raw footage into pure art.",
    rating: 5,
  },
  {
    _id: '2',
    name: 'Priya Sharma',
    role: 'Brand Manager',
    company: 'LuxeFashion India',
    message: 'We hired Shriram for our product campaign and were blown away. His ability to tell a brand story through visuals is unmatched. The commercial went viral within days.',
    rating: 5,
  },
  {
    _id: '3',
    name: 'Arjun Mehta',
    role: 'Wedding Client',
    company: '',
    message: 'Our wedding film makes us cry every time we watch it. Shriram captures emotions that you thought no camera could hold. Absolutely stunning, timeless work.',
    rating: 5,
  },
  {
    _id: '4',
    name: 'Neha Kapoor',
    role: 'Music Artist',
    company: 'Independent Artist',
    message: "Shriram shot and edited my music video with incredible creativity. His drone work added a cinematic dimension that elevated the entire production to another level.",
    rating: 5,
  },
  {
    _id: '5',
    name: 'Vikram Singh',
    role: 'Head of Content',
    company: 'WTL Productions',
    message: "Working with Shriram at WTL for 5 years has been a privilege. His technical mastery combined with his creative vision makes him truly irreplaceable in any production.",
    rating: 5,
  },
]
